### ISSUE TITLE
UI: Overlapping Logo and Hyperlink in Card Component

### ISSUE THREAD

**Issue by AnuravModak** [ApiBR/vagas-aggregator-ui#109]
**Describe the bug**
The current UI layout presents an issue where a logo and a hyperlink are overlapping with the date and timestamp as you can see in the image below within the card component. This overlap is negatively affecting the visual and functional aspects of the user interface.

<img width="221" alt="image" src="https://github.com/ApiBR/vagas-aggregator-ui/assets/79191029/b4cf32f4-5a17-4041-8b12-bc0a9524ffdf">

**To Reproduce**
1. Navigate to [here]( https://apibr.com/ui/vagas?organizations=CangaceirosDevel)
2. Observe the logo and the hyperlink within the card, i think its a github logo (not sure though what its called!!) with "blankapf" as text which shall be linked to some other resource possibly.
3. Note that the logo and hyperlink are overlapping with date and timestamp, causing a visual inconsistency and potential clickability issues.

**Expected behavior**
The logo and hyperlink should be appropriately spaced and not overlap, ensuring a clean and user-friendly design. Users should be able to interact with the hyperlink without any visual hindrance or any kind of hindrance.

 - Browser [chrome]
 - Version [current version that is deployed]

**Additional context**
I would be glad if this bug is assigned to me.

Please feel free to use comment section for any further discussion.

**Comment by AnuravModak** [comment]
I have completed the work and fixed the issue/bug.

**Here is an overview of my work and some basic justifications:**

1. Here is how your website looks right now:
![image](https://github.com/ApiBR/vagas-aggregator-ui/assets/79191029/0df6ba92-fe8d-4a12-8234-7d50595c56de)

And here's how it will look after merging the changes from my side:
![image](https://github.com/ApiBR/vagas-aggregator-ui/assets/79191029/50f3f373-e778-41f1-9a6b-45cdd740fbf5)

Now, I have moved the author's link just beside their repository link because, when I was trying to prevent the overlapping, there was some loss of data with the timestamp tags or with the author's name as shown in the image below:
<img width="575" alt="image" src="https://github.com/ApiBR/vagas-aggregator-ui/assets/79191029/29ae7cef-e66e-4df5-aa25-68774be7cd2f">

As you can see, the author's name is partially cut with that approach, so I decided to keep it with the repository link/button. Also, it is more ergonomically suitable to place it there.

2. Secondly, I also changed the anchor tag to a button as it was more user-friendly.

3. After making the necessary changes, I also conducted testing, and these are the results:
   For all the test cases:
   ![image](https://github.com/ApiBR/vagas-aggregator-ui/assets/79191029/785216cd-2c4e-420b-8684-55ef4fead1ee)

   Then, I checked if there were any failed test cases, and there were none. Refer to the image below:
   ![image](https://github.com/ApiBR/vagas-aggregator-ui/assets/79191029/c842a28f-94c1-4a88-8fa6-1de33b9bb6dc)
   You can also test the same from your side.

I am raising a PR referencing this issue. Kindly review it and let me know.

**Comment by guibranco** [comment]
Thanks for the effort @AnuravModak, nice job!
