### ISSUE TITLE
Timestamp Component Overflows Card in IssueItem in recrutadores

### ISSUE THREAD

**Issue by AnuravModak** [ApiBR/vagas-aggregator-ui#116]
**Describe the bug**
The timestamp component within the card is overflowing and extending beyond the card boundaries. This is causing a visual misalignment and disruption in the layout of the card. The timestamp should remain within the designated card area to maintain a consistent and aesthetically pleasing design.

**To Reproduce**
1. Go to [here](https://apibr.com/ui/vagas/recrutadores)
2. Scroll to see the bug in the cards.

**Expected behavior**
The timestamp component within the card should be appropriately styled and positioned to fit comfortably within the confines of the card. It should align with the card's layout and not extend beyond its edges. This ensures a visually pleasing presentation and maintains the overall coherence of the card's design.

**Screenshots**
![image](https://github.com/ApiBR/vagas-aggregator-ui/assets/79191029/778a7793-7207-476b-984f-c2c869171d1c)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [chrome, edge]
 - Current Version

**Additional context**
Currently working on this issue. Kindly, assign me this issue.
Please feel free to use comment section to start any discussion or ask any questions.

**Comment by guibranco** [comment]
Merged!
