### ISSUE TITLE
Missing Error handling in the whole react-application

### ISSUE THREAD

**Issue by AnuravModak** [ApiBR/vagas-aggregator-ui#118]
**Is your feature request related to a problem? Please describe.**
So this feature is related to a problem, there is no proper error-handling and this is necessary for an deployed application because, if by any chance any error occurs the whole application will crash, preventing the app from becoming unresponsive or crashing we need error-handling.

**Describe the solution you'd like**
Centralized Error Handling: Global error boundaries allow you to centralize error handling logic in one place (e.g., at the app's entry point), making it easier to manage and maintain error-handling code.

Consistency: With a global error boundary, you can ensure a consistent error-handling strategy throughout your application. You don't have to repeat error-handling code in multiple places.

**Describe alternatives you've considered**
A descent alternative could be to use simple try and catch blocks, but that won't be providing us robustness that is required to be maintained in a deployed application.

**Additional context**
Please feel free to ask any questions and I would be happy to add this feature to enhance the robustness of the application, kindly assign me this issue.

**Comment by guibranco** [comment]
Would you like to work on this one @AnuravModak ?

**Comment by AnuravModak** [comment]
yeah, please assign this to me

**Comment by guibranco** [comment]
Thanks @AnuravModak, amazing job!
